"""initial schema

Revision ID: 04bef5d82379
Revises: 
Create Date: 2026-09-30 16:33:07.094185
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '04bef5d82379'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=True)
    op.create_table('models',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('input_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('provider', 'name', name='uq_models_provider_name')
    )
    op.create_index(op.f('ix_models_created_at'), 'models', ['created_at'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_index(op.f('ix_models_provider'), 'models', ['provider'], unique=False)
    op.create_table('anomalies',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_low', sa.Float(), nullable=True),
    sa.Column('expected_high', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('peer_median', sa.Float(), nullable=True),
    sa.Column('peer_p95', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_method', sa.String(length=64), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_anomalies_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index('ix_anomalies_app_detected', 'anomalies', ['application_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_created_at'), 'anomalies', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_trace_id'), 'anomalies', ['trace_id'], unique=False)
    op.create_index('ix_anomalies_type_severity', 'anomalies', ['anomaly_type', 'severity'], unique=False)
    op.create_table('documents',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('parent_external_id', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('application_id', 'external_id', name='uq_documents_app_external')
    )
    op.create_index('ix_documents_app_source', 'documents', ['application_id', 'source'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('evaluation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('num_queries', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_evaluation_runs_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_eval_runs_app_created', 'evaluation_runs', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_eval_runs_dataset', 'evaluation_runs', ['dataset_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_created_at'), 'evaluation_runs', ['created_at'], unique=False)
    op.create_table('optimization_recommendations',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_optimization_recommendations_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_recommendations'))
    )
    op.create_index(op.f('ix_optimization_recommendations_category'), 'optimization_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_created_at'), 'optimization_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_priority'), 'optimization_recommendations', ['priority'], unique=False)
    op.create_index('ix_reco_app_created', 'optimization_recommendations', ['application_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_users_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('application_id', 'external_id', name='uq_users_app_external')
    )
    op.create_index('ix_users_app_external', 'users', ['application_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('context_relevance', sa.Float(), nullable=True),
    sa.Column('answer_relevance', sa.Float(), nullable=True),
    sa.Column('citation_coverage', sa.Float(), nullable=True),
    sa.Column('unsupported_claim_ratio', sa.Float(), nullable=True),
    sa.Column('judge_faithfulness', sa.Float(), nullable=True),
    sa.Column('judge_answer_relevance', sa.Float(), nullable=True),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('judge_rationale', sa.Text(), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_answer_evaluations_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_evaluations'))
    )
    op.create_index('ix_answer_eval_run', 'answer_evaluations', ['run_id'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_created_at'), 'answer_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_trace_id'), 'answer_evaluations', ['trace_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevant_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_results_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results'))
    )
    op.create_index('ix_eval_results_run', 'evaluation_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_created_at'), 'evaluation_results', ['created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('baseline_run_id', sa.UUID(), nullable=True),
    sa.Column('winner_variant', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_experiments_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['evaluation_runs.id'], name=op.f('fk_experiments_baseline_run_id_evaluation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_table('traces',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_external_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('agent_iterations', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_traces_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_traces_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traces')),
    sa.UniqueConstraint('application_id', 'trace_id', name='uq_traces_app_trace')
    )
    op.create_index(op.f('ix_traces_agent_name'), 'traces', ['agent_name'], unique=False)
    op.create_index('ix_traces_app_start', 'traces', ['application_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_traces_created_at'), 'traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_traces_session_id'), 'traces', ['session_id'], unique=False)
    op.create_index('ix_traces_start_status', 'traces', ['start_time', 'status'], unique=False)
    op.create_index(op.f('ix_traces_start_time'), 'traces', ['start_time'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=False)
    op.create_index(op.f('ix_traces_user_external_id'), 'traces', ['user_external_id'], unique=False)
    op.create_index('ix_traces_user_start', 'traces', ['user_id', 'start_time'], unique=False)
    op.create_table('experiment_variants',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_variants_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_experiment_variants_run_id_evaluation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_variants'))
    )
    op.create_index(op.f('ix_experiment_variants_created_at'), 'experiment_variants', ['created_at'], unique=False)
    op.create_table('spans',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_span_id'], ['spans.id'], name=op.f('fk_spans_parent_span_id_spans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_spans_trace_id_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spans'))
    )
    op.create_index(op.f('ix_spans_created_at'), 'spans', ['created_at'], unique=False)
    op.create_index(op.f('ix_spans_start_time'), 'spans', ['start_time'], unique=False)
    op.create_index('ix_spans_trace_start', 'spans', ['trace_id', 'start_time'], unique=False)
    op.create_table('llm_calls',
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('span_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('completion', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_llm_calls_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_llm_calls_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_llm_calls_span_id_spans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_llm_calls_trace_id_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_app_time', 'llm_calls', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_created_at'), 'llm_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_model_name'), 'llm_calls', ['model_name'], unique=False)
    op.create_index('ix_llm_calls_model_time', 'llm_calls', ['model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_provider'), 'llm_calls', ['provider'], unique=False)
    op.create_index('ix_llm_calls_trace', 'llm_calls', ['trace_id'], unique=False)
    op.create_table('retrieval_calls',
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('span_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('retriever', sa.String(length=64), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('num_results', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_retrieval_calls_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_retrieval_calls_span_id_spans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_retrieval_calls_trace_id_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_calls'))
    )
    op.create_index('ix_retrieval_app_time', 'retrieval_calls', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_calls_created_at'), 'retrieval_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_calls_retriever'), 'retrieval_calls', ['retriever'], unique=False)
    op.create_index('ix_retrieval_trace', 'retrieval_calls', ['trace_id'], unique=False)
    op.create_table('retrieved_documents',
    sa.Column('retrieval_call_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('bm25_score', sa.Float(), nullable=True),
    sa.Column('vector_score', sa.Float(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_call_id'], ['retrieval_calls.id'], name=op.f('fk_retrieved_documents_retrieval_call_id_retrieval_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieved_documents'))
    )
    op.create_index('ix_retrieved_docs_call_rank', 'retrieved_documents', ['retrieval_call_id', 'rank'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_created_at'), 'retrieved_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_document_id'), 'retrieved_documents', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieved_documents_document_id'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_created_at'), table_name='retrieved_documents')
    op.drop_index('ix_retrieved_docs_call_rank', table_name='retrieved_documents')
    op.drop_table('retrieved_documents')
    op.drop_index('ix_retrieval_trace', table_name='retrieval_calls')
    op.drop_index(op.f('ix_retrieval_calls_retriever'), table_name='retrieval_calls')
    op.drop_index(op.f('ix_retrieval_calls_created_at'), table_name='retrieval_calls')
    op.drop_index('ix_retrieval_app_time', table_name='retrieval_calls')
    op.drop_table('retrieval_calls')
    op.drop_index('ix_llm_calls_trace', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_provider'), table_name='llm_calls')
    op.drop_index('ix_llm_calls_model_time', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_model_name'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_created_at'), table_name='llm_calls')
    op.drop_index('ix_llm_calls_app_time', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_spans_trace_start', table_name='spans')
    op.drop_index(op.f('ix_spans_start_time'), table_name='spans')
    op.drop_index(op.f('ix_spans_created_at'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_experiment_variants_created_at'), table_name='experiment_variants')
    op.drop_table('experiment_variants')
    op.drop_index('ix_traces_user_start', table_name='traces')
    op.drop_index(op.f('ix_traces_user_external_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_start_time'), table_name='traces')
    op.drop_index('ix_traces_start_status', table_name='traces')
    op.drop_index(op.f('ix_traces_session_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_created_at'), table_name='traces')
    op.drop_index('ix_traces_app_start', table_name='traces')
    op.drop_index(op.f('ix_traces_agent_name'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_evaluation_results_created_at'), table_name='evaluation_results')
    op.drop_index('ix_eval_results_run', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_answer_evaluations_trace_id'), table_name='answer_evaluations')
    op.drop_index(op.f('ix_answer_evaluations_created_at'), table_name='answer_evaluations')
    op.drop_index('ix_answer_eval_run', table_name='answer_evaluations')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('ix_users_app_external', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_reco_app_created', table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_priority'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_created_at'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_category'), table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    op.drop_index(op.f('ix_evaluation_runs_created_at'), table_name='evaluation_runs')
    op.drop_index('ix_eval_runs_dataset', table_name='evaluation_runs')
    op.drop_index('ix_eval_runs_app_created', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index('ix_documents_app_source', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_anomalies_type_severity', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_trace_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_created_at'), table_name='anomalies')
    op.drop_index('ix_anomalies_app_detected', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_models_provider'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_created_at'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
