"""Pydantic schemas for the RAGOps API.

Split by concern so the collector contract (ingest) stays independent of the
read schemas the dashboard consumes.
"""

from app.schemas.analytics import (
    CostAnalytics,
    CostQualityReport,
    DashboardOverview,
    LatencyAnalytics,
    ModelComparison,
    TokenAnalytics,
    TokenEfficiencyReport,
)
from app.schemas.common import (
    BreakdownItem,
    ErrorResponse,
    HealthResponse,
    MessageResponse,
    ORMModel,
    Page,
    TimeSeriesPoint,
)
from app.schemas.evaluation import (
    AnswerEvaluationItem,
    AnswerEvaluationRequest,
    AnswerEvaluationResult,
    AnswerEvaluationSummary,
    ClaimEvaluation,
    ConfigDifference,
    EvalExample,
    EvaluationRunDetail,
    EvaluationRunSummary,
    MetricDelta,
    PerQueryResult,
    RegressionReport,
    RetrievalEvaluationRequest,
    RetrievalMetrics,
)
from app.schemas.ingest import (
    BatchIngest,
    GenerationIn,
    IngestResponse,
    RetrievalIn,
    RetrievedDocumentIn,
    SpanIn,
    TraceCreate,
)
from app.schemas.insights import (
    AnomalyDetectRequest,
    AnomalyDetectResponse,
    AnomalyOut,
    ApplicationOut,
    ExperimentCreate,
    ExperimentOut,
    ExperimentVariantIn,
    ExperimentVariantOut,
    ModelOut,
    ModelUpsert,
    RecommendationGenerateRequest,
    RecommendationOut,
)
from app.schemas.trace import (
    LLMCallOut,
    RetrievedDocumentOut,
    RetrievalOut,
    SpanOut,
    TraceDetail,
    TraceSummary,
)
from app.schemas.tenancy import (
    ApiKeyCreate,
    ApiKeyOut,
    CreatedApiKey,
    OrganizationCreate,
    OrganizationOut,
)

__all__ = [
    "AnomalyDetectRequest",
    "AnomalyDetectResponse",
    "AnomalyOut",
    "AnswerEvaluationItem",
    "AnswerEvaluationRequest",
    "AnswerEvaluationResult",
    "AnswerEvaluationSummary",
    "ApiKeyCreate",
    "ApiKeyOut",
    "ApplicationOut",
    "BatchIngest",
    "BreakdownItem",
    "ClaimEvaluation",
    "ConfigDifference",
    "CostAnalytics",
    "CostQualityReport",
    "CreatedApiKey",
    "DashboardOverview",
    "ErrorResponse",
    "EvalExample",
    "EvaluationRunDetail",
    "EvaluationRunSummary",
    "ExperimentCreate",
    "ExperimentOut",
    "ExperimentVariantIn",
    "ExperimentVariantOut",
    "GenerationIn",
    "HealthResponse",
    "IngestResponse",
    "LatencyAnalytics",
    "LLMCallOut",
    "MessageResponse",
    "MetricDelta",
    "ModelComparison",
    "ModelOut",
    "ModelUpsert",
    "ORMModel",
    "OrganizationCreate",
    "OrganizationOut",
    "Page",
    "PerQueryResult",
    "RecommendationGenerateRequest",
    "RecommendationOut",
    "RegressionReport",
    "RetrievalEvaluationRequest",
    "RetrievalIn",
    "RetrievalMetrics",
    "RetrievalOut",
    "RetrievedDocumentIn",
    "RetrievedDocumentOut",
    "SpanIn",
    "SpanOut",
    "TimeSeriesPoint",
    "TokenAnalytics",
    "TokenEfficiencyReport",
    "TraceCreate",
    "TraceDetail",
    "TraceSummary",
]
