"""The RAGOps application factory and its lifespan.

Three decisions here are load-bearing, and the reasoning is worth stating once
here rather than repeating in each call site.

**The lifespan verifies, it does not create.** ``_check_schema`` connects and asks
whether every table Alembic says should exist is actually there, and reports the
names of the ones that are not. It does not call ``create_all``: this project owns
its schema with Alembic (``alembic/versions/``), and a service that quietly
materialises tables at start-up makes a failed migration look like a working
deployment while diverging from every other environment. A fresh checkout runs
``alembic upgrade head``; the message here says so, naming the tables that are
missing, instead of the API coming up and 500-ing on the first query.

**Redis is warmed, and its absence is not fatal.** The cache is an accelerator:
every caller treats a miss as "compute it again". So the lifespan pings Redis,
records the outcome, and carries on either way — a missing Redis costs latency,
not availability, and refusing to boot over it would make a single optional
dependency into a hard requirement. The result is reported on ``/api/health``
rather than swallowed, so the degradation is visible to whoever needs to see it.

**Middleware order is CORS, then request context, then the error handler.** CORS
is outermost so that a preflight never reaches anything that could fail, and so
that a response generated by the error handler below still carries its CORS
headers — an inner-only CORS turns every 500 into an opaque CORS failure in the
browser. Request context sits above the error handler so a request id exists by
the time an unhandled error is logged, which is what makes that log line
correlatable with the request that caused it.
"""

from __future__ import annotations

import asyncio
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import ORJSONResponse
from sqlalchemy import inspect

from app.api.v1 import api_router
from app.config import settings
from app.core.cache import close_redis, ping as redis_ping
from app.core.database import SessionLocal, dispose_engine
from app.core.logging import configure_logging, get_logger
from app.core.middleware import (
    APIErrorHandlerMiddleware,
    RequestContextMiddleware,
    TraceContextMiddleware,
)
from app.models.base import Base

# Imported for the side effect of registering every table on ``Base.metadata``.
# Without it ``_check_schema`` would compare the database against a metadata that
# contains nothing and report a healthy, empty schema.
import app.models  # noqa: F401  isort:skip

logger = get_logger("ragops.app")

#: How long start-up will wait on the database before giving up. Bounded because
#: an orchestrator needs the container to either become ready or restart it; a
#: start-up that blocks forever on an unreachable database turns one bad
#: connection string into a pod that never reports anything at all.
STARTUP_TIMEOUT_SECONDS = 10.0


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Start-up checks, and the shutdown that undoes them.

    The start-up checks are reported, not enforced: the service comes up and
    ``/api/health`` tells the truth about what it can and cannot reach. A
    telemetry backend that will not serve an empty dashboard until Postgres
    answers is harder to operate than one that starts and explains itself.
    """
    configure_logging()
    logger.info(
        "app.startup",
        environment=settings.environment,
        api_prefix=settings.api_v1_prefix,
    )

    app.state.schema = await _check_schema()
    app.state.redis = await _warm_cache()

    logger.info(
        "app.ready",
        schema=app.state.schema,
        redis=app.state.redis,
    )

    yield

    await close_redis()
    await dispose_engine()
    logger.info("app.shutdown")


async def _check_schema() -> dict[str, Any]:
    """Report which of the expected tables are present, by asking.

    Compares ``Base.metadata`` against the live database with SQLAlchemy's
    inspector rather than trusting a migration stamp: a database can be stamped
    ``head`` and still be missing a table, and a missing table surfaces as a 500
    on one endpoint while everything else looks fine. Names the missing tables so
    the remedy is in the message.
    """
    started = time.perf_counter()
    expected = set(Base.metadata.tables)
    try:
        async with asyncio.timeout(STARTUP_TIMEOUT_SECONDS):
            async with SessionLocal() as session:
                connection = await session.connection()
                # ``run_sync`` runs a sync function on the async connection's
                # greenlet, which is the only way to get the DBAPI connection
                # the inspector needs.
                def get_names(sync_connection: Any) -> set[str]:
                    return set(inspect(sync_connection).get_table_names())

                present = await connection.run_sync(get_names)
    except Exception as exc:  # noqa: BLE001 - the outcome is reported, not raised
        elapsed_ms = (time.perf_counter() - started) * 1000.0
        logger.warning("app.schema.unreachable", error=str(exc), error_type=type(exc).__name__)
        return {
            "ok": False,
            "reachable": False,
            "error": f"{type(exc).__name__}: {exc}",
            "latency_ms": round(elapsed_ms, 2),
            "missing_tables": None,
        }

    missing = sorted(expected - present)
    elapsed_ms = (time.perf_counter() - started) * 1000.0
    if missing:
        logger.warning("app.schema.missing", missing=missing)
    return {
        "ok": not missing,
        "reachable": True,
        "latency_ms": round(elapsed_ms, 2),
        "expected_table_count": len(expected),
        "missing_tables": missing,
    }


async def _warm_cache() -> dict[str, Any]:
    """Connect to Redis once, and record whether it is usable.

    Never raises. The cache layer already degrades to a miss on every code path,
    and a start-up that refused to finish because an accelerator was down would
    contradict that. The returned state is what ``/api/health`` reports, so the
    degradation is a fact on the API rather than a mystery in the logs.
    """
    started = time.perf_counter()
    try:
        reachable = await redis_ping()
    except Exception as exc:  # noqa: BLE001 - documented never to raise, but honoured
        elapsed_ms = (time.perf_counter() - started) * 1000.0
        logger.warning("app.redis.error", error=str(exc), error_type=type(exc).__name__)
        return {
            "reachable": False,
            "latency_ms": round(elapsed_ms, 2),
            "error": f"{type(exc).__name__}: {exc}",
        }

    elapsed_ms = (time.perf_counter() - started) * 1000.0
    if reachable:
        logger.info("app.redis.ready", url=settings.redis_url, latency_ms=round(elapsed_ms, 2))
    else:
        # Expected in a default checkout: Redis is optional by design, and this
        # line is the difference between "degraded on purpose" and "broken".
        logger.warning(
            "app.redis.unavailable",
            url=settings.redis_url,
            detail="cache disabled; every analytics read will be recomputed",
        )
    return {"reachable": reachable, "latency_ms": round(elapsed_ms, 2)}


def create_app() -> FastAPI:
    """Build the application.

    A factory rather than a module-level instance so tests can build an app with
    different settings, and so importing this module has no side effects — the
    ``app = create_app()`` at the bottom exists for uvicorn's ``app.main:app``
    and is the only module-level object.
    """
    application = FastAPI(
        title=settings.app_name,
        version=APP_VERSION,
        description=(
            "Observability for RAG systems: ingest traces, score retrieval, "
            "judge answers, and report what the traffic actually cost.\n\n"
            "**Authentication.** Send `X-API-Key`. A key matching the shared "
            "`RAGOPS_API_KEY` is the platform principal and sees everything; a key "
            "minted through `/api/organizations` resolves to its own company and "
            "sees only that company's data; a key matching nothing is rejected with "
            "401 rather than falling back. Omitting the header entirely also "
            "resolves to the platform principal, which is what lets the dashboard "
            "work before anything is instrumented."
        ),
        default_response_class=ORJSONResponse,
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
    )

    # Outermost first. See the module docstring for why this order is not
    # arbitrary: a 500 generated below must still reach the browser as JSON with
    # CORS headers attached, and a logged error must carry its request id.
    application.add_middleware(APIErrorHandlerMiddleware)
    application.add_middleware(TraceContextMiddleware)
    application.add_middleware(RequestContextMiddleware)
    application.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
        expose_headers=["X-Request-ID", "X-Response-Time-ms"],
    )

    application.include_router(api_router, prefix=settings.api_v1_prefix)
    return application


#: Reported by ``/api/health``. There is no version in settings, and inventing a
#: second source of truth for it here would be worse than stating plainly that
#: this is the API's own version rather than the project's package version.
APP_VERSION = "0.1.0"

app = create_app()
